# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_penlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penlist',
        ),
    ]
