# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_penlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('Customer', models.CharField(max_length=100)),
            ],
        ),
    ]
