# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-11 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=500),
        ),
    ]
