# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-11 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190811_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
