# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190817_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
