# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190816_2138'),
        ('app1', '0012_auto_20190817_1324'),
    ]

    operations = [
    ]
